---
name: Remove a published release [WARNING]

# This is only expected to be invoked on-demand by a specific user.
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: The version to remove from release.
        type: string

jobs:

  remove-release-packages-s3:
    name: S3 - remove release
    runs-on: ubuntu-18.04 # no createrepo on Ubuntu 20.04
    environment: release
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup runner
      run: |
        sudo apt-get install debsigs createrepo aptly rsync
      shell: bash

    - name: Import GPG key for signing
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v4
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

    - name: Sync packages from bucket on S3
      run: |
        mkdir -p packaging/releases
        aws s3 sync "s3://${{ secrets.AWS_S3_BUCKET_RELEASE }}" packaging/releases/ --no-progress
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      shell: bash

    - name: GPG set up keys for signing
      run: |
        gpg --export -a "${{ steps.import_gpg.outputs.name }}" > packaging/releases/fluentbit.key
        rpm --import packaging/releases/fluentbit.key
      shell: bash

    - name: Remove versions and update repo info
      run: |
        packaging/remove-version.sh "$VERSION" packaging/releases/
      env:
        GPG_KEY: ${{ steps.import_gpg.outputs.name }}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_RELEASE }}
      shell: bash

    - name: Sync to release bucket on S3
      run: |
        aws s3 sync packaging/releases/ "s3://${{ secrets.AWS_S3_BUCKET_RELEASE }}" --delete --follow-symlinks --no-progress
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      shell: bash

  remove-release-packages-server:
    name: fluentbit.io - upload packages
    runs-on: ubuntu-18.04 # failures with AWS client on latest
    environment: release
    needs: remove-release-packages-s3
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup runner
      run: |
        sudo apt-get install rsync
      shell: bash

    - name: Hashed known hosts value
      id: known_hosts
      run: |
          OUTPUT=$(ssh-keyscan -H ${{ secrets.FLUENTBITIO_HOST }})
          echo ::set-output name=OUTPUT::$OUTPUT

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.FLUENTBITIO_SSHKEY }}
        known_hosts: ${{ steps.known_hosts.outputs.OUTPUT }}

    - name: Sync packages from release bucket on S3
      run: |
        mkdir -p packaging/releases
        aws s3 sync "s3://$BUCKET" packaging/releases/ --no-progress
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # Replace with staging bucket if required later
        BUCKET: ${{ secrets.AWS_S3_BUCKET_RELEASE }}
      shell: bash

    - name: Upload to build server
      run: |
        ssh $USERNAME@$HOST mkdir -p /home/$USERNAME/s3-release
        rsync --include="*/" --include="*.rpm" --include="*.deb" --exclude="*" -amvz packaging/releases/ $USERNAME@$HOST:/home/$USERNAME/s3-release
      env:
        HOST: ${{ secrets.FLUENTBITIO_HOST }}
        USERNAME: ${{ secrets.FLUENTBITIO_USERNAME }}
      shell: bash
