---
name: Release from staging

# This is only expected to be invoked on-demand by a specific user.
on:
  workflow_dispatch:

jobs:
  call-test-windows-packaging:
    name: Windows package tests
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download packages locally
      run: |
        Invoke-WebRequest -Uri $EXE_SOURCE -OutFile C:\temp\fluent-bit.exe
        Invoke-WebRequest -Uri $ZIP_SOURCE -OutFile C:\temp\fluent-bit.zip
      shell: powershell
      env:
        EXE_SOURCE: https://fluentbit.io/releases/1.8/td-agent-bit-1.8.11-win64.exe
        ZIP_SOURCE: https://fluentbit.io/releases/1.8/td-agent-bit-1.8.11-win64.zip

    - name: Install zip locally to test
      run: |
        Expand-Archive td-agent-bit-1.8.11-win64.zip C:\temp\fluent-bit.zip
      shell: powershell

    - name: Run zip version with simple config
      run: |
         Start-Process -NoNewWindow -FilePath .\bin\fluent-bit.exe -ArgumentList "-i", "dummy". "-o", "stdout"
      shell: powershell

    - name: Run zip version with default config
      run: |
         Start-Process -NoNewWindow -FilePath .\bin\fluent-bit.exe
      shell: powershell